//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.14 at 03:16:28 PM AMT 
//


package br.ufmt.publica;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for solicitaPublicacao complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="solicitaPublicacao">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="publica" type="{}publica" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "solicitaPublicacao", propOrder = {
    "publica"
})
public class SolicitaPublicacao {

    protected Publica publica;

    /**
     * Gets the value of the publica property.
     * 
     * @return
     *     possible object is
     *     {@link Publica }
     *     
     */
    public Publica getPublica() {
        return publica;
    }

    /**
     * Sets the value of the publica property.
     * 
     * @param value
     *     allowed object is
     *     {@link Publica }
     *     
     */
    public void setPublica(Publica value) {
        this.publica = value;
    }

}
