//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.14 at 03:16:55 PM AMT 
//


package br.ufmt.busca;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for solicitaArquivoBusca complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="solicitaArquivoBusca">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="busca" type="{}busca" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "solicitaArquivoBusca", propOrder = {
    "busca"
})
public class SolicitaArquivoBusca {

    protected Busca busca;

    /**
     * Gets the value of the busca property.
     * 
     * @return
     *     possible object is
     *     {@link Busca }
     *     
     */
    public Busca getBusca() {
        return busca;
    }

    /**
     * Sets the value of the busca property.
     * 
     * @param value
     *     allowed object is
     *     {@link Busca }
     *     
     */
    public void setBusca(Busca value) {
        this.busca = value;
    }

}
