//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.14 at 03:15:55 PM AMT 
//


package br.ufmt.dados;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.ufmt.dados package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Resposta_QNAME = new QName("", "resposta");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.ufmt.dados
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Resposta }
     * 
     */
    public Resposta createResposta() {
        return new Resposta();
    }

    /**
     * Create an instance of {@link DadosArquivo }
     * 
     */
    public DadosArquivo createDadosArquivo() {
        return new DadosArquivo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Resposta }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "resposta")
    public JAXBElement<Resposta> createResposta(Resposta value) {
        return new JAXBElement<Resposta>(_Resposta_QNAME, Resposta.class, null, value);
    }

}
