//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.14 at 03:15:55 PM AMT 
//


package br.ufmt.dados;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for resposta complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resposta">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dadosArquivo" type="{}dadosArquivo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resposta", propOrder = {
    "dadosArquivo"
})
public class Resposta {

    protected DadosArquivo dadosArquivo;

    /**
     * Gets the value of the dadosArquivo property.
     * 
     * @return
     *     possible object is
     *     {@link DadosArquivo }
     *     
     */
    public DadosArquivo getDadosArquivo() {
        return dadosArquivo;
    }

    /**
     * Sets the value of the dadosArquivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DadosArquivo }
     *     
     */
    public void setDadosArquivo(DadosArquivo value) {
        this.dadosArquivo = value;
    }

}
