//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.13 at 03:52:31 PM AMT 
//


package br.ufmt.requisicao;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for solicitaArquivo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="solicitaArquivo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requisita" type="{}requisitaArquivo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "solicitaArquivo", propOrder = {
    "requisita"
})
public class SolicitaArquivo {

    protected RequisitaArquivo requisita;

    /**
     * Gets the value of the requisita property.
     * 
     * @return
     *     possible object is
     *     {@link RequisitaArquivo }
     *     
     */
    public RequisitaArquivo getRequisita() {
        return requisita;
    }

    /**
     * Sets the value of the requisita property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequisitaArquivo }
     *     
     */
    public void setRequisita(RequisitaArquivo value) {
        this.requisita = value;
    }

}
